シーンの追加
kiyosumi874/MyDxLibGame3D pull request #1
Opened 2022-09-23 03:53 UTC by kiyosumi874

構造が少しわかりにくいかもしれませんがObstructとやっていることは変わらないと思います

2022-09-23 04:19 UTC, tricore-t-yui requested changes
コーディングの見た目合わせてくださいー

2022-09-23 04:19 UTC, tricore-t-yui commented on src/Macro.h
> +#define SAFE_DELETE(p) { if(p) { delete p; p = nullptr; } }
[nits]
マクロってなんの名前かわからんのでユーティリティとかがいいかも

2022-09-23 04:19 UTC, tricore-t-yui commented on src/Scene/PlayScene.cpp
> +	pCamera = new Camera;
[mist]
p〇〇等、接頭子つけるコーディングルールにはしてないので統一してください

2022-09-23 04:19 UTC, tricore-t-yui commented on src/Scene/PlayScene.cpp
> +	SAFE_DELETE(pCamera);
[must]
セーフデリート追加するのはいいけど、するなら全クラスそうしてください

2022-09-23 04:19 UTC, tricore-t-yui commented on src/Scene/ResultScene.cpp
> +}
[must]
処理無しなら処理無しとコメント

2022-09-23 04:22 UTC, kiyosumi874 commented on src/Scene/PlayScene.cpp
> +	SAFE_DELETE(pCamera);
全クラスそうします

2022-09-23 04:23 UTC, kiyosumi874 commented on src/Scene/ResultScene.cpp
> +}
以後気を付けます

2022-09-23 04:23 UTC, kiyosumi874 commented on src/Scene/PlayScene.cpp
> +	pCamera = new Camera;
承知しました

2022-09-23 04:47 UTC, kiyosumi874 commented
コーディング規則をもとのソースコードに合わせました
コードレビューお願いします！

2022-09-24 02:36 UTC, tricore-t-yui requested changes
[must]
文字コードが変更されているので差分がえげつないことになっています
utf-8に修正してください

2022-09-24 02:40 UTC, tricore-t-yui requested changes

2022-09-24 02:40 UTC, tricore-t-yui commented on src/main.cpp
> +void SceneChanger(Scene*& scene, SceneType now, SceneType prev)
[must]
SceneChanger＝「シーンを切り替える人」なので関数の命名規則である「動詞＋名詞」になっていない。
この場合CheckAndChangeSceneでは

2022-09-24 05:35 UTC, tricore-t-yui requested changes

2022-09-24 05:35 UTC, tricore-t-yui commented on src/main.cpp
> +void ChangeScene(Scene*& scene, SceneType now)
[must]
ChangeSceneだとシーン切り替えです
一回だけ呼ぶ関数の名前にしか見えません

2022-09-24 06:59 UTC, merged